---
- hosts: localhost
  sudo: yes 
  tasks:
  - name: Install packages
    apt: name={{item}} state=installed
    with_items:
    - git
    - vim
    - gimp
    - guake
    - apache2
    - mysql-server
    - php
    - libapache2-mod-php
    - php-mysql
  
  - name: Install Vim-Plug
    command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - name: Get vim configs from github
    get_url:
      url: https://raw.githubusercontent.com/RobertHosking/sys-configs/master/dots/.vimrc
      dest: ~/
      mode: 0440


